version: "3"
services:
  broadcaster:
    image: broadcaster:0.1.0
    ports:
      - "8080:8080"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-network
    depends_on:
      - kafka